import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
  },
  rectangle: {
    height: '100%',
    width: '100%',
    flex: 1,
    opacity: 0.88,
    backgroundColor: '#09121C',
    position: 'absolute',
    zIndex: 1,
  },
  backgroundOverlay: {
    height: '100%',
    width: '100%',
    flex: 1,
    position: 'absolute',
    zIndex: 2,
  },
  logoPlacement: {
    justifyContent: 'center',
    zIndex: 3,
    position: 'absolute',
    marginTop: 25,
    marginLeft: 15,
  },
  logoPlacementMain: {
    justifyContent: 'center',
    zIndex: 3,
    position: 'absolute',
    marginTop: 80,
    marginLeft: 65,
  },
  logoPlacementName: {
    zIndex: 3,
    width: 115,
    height: 45,
    position: 'absolute',
    marginTop: 40,
    marginLeft: 100,
  },
  logoHeadingMain: {
    zIndex: 3,
    position: 'absolute',
    marginTop: 175,
    marginLeft: 45,
    marginRight: 45,
    marginBottom: 50,
    alignItems: "center",
    alignSelf: "center",
  },
  logoHeading: {
    fontSize: 30,
    color: '#fff',
    marginBottom: 40,
    
  },
  TextInputFields: {
    zIndex: 3,
    position: 'absolute',
    width: '89%',
    flex: 1,
    borderRadius: 25,
    marginLeft: 25,
    marginTop: 289,
    marginBottom: 20,
  },
  email: {
    backgroundColor: 'white',
  },
  emailIcon: {
    width: '100%',
  },
  password: {
    color: 'white',
  },
  LoginFields: {
    zIndex: 3,
    color: 'white',
    marginBottom: 20,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    borderBottomLeftRadius: 15,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    borderBottomWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.68)',
    borderLeftWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.68)',
    borderRightWidth: 1,
    borderTopWidth: 1,
    paddingLeft: 25,
  },
  ForgetPassword: {
    alignContent: 'center',
    alignSelf: 'center',
    marginTop: 10,
  },
  submit: {
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: '#3369ff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    shadowColor: '#3369ff',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
  },
  submitText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 17,
  },
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  text: {
    color: '#161924',
    fontSize: 20,
    fontWeight: '500',
  },
});
